package com.example.madrid.madrid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@CrossOrigin(origins = {"http://localhost:3000", "http://localhost:3001"})
@Controller // This means that this class is a Controller
@RequestMapping(path="/restaurants") // This means URL's start with /demo (after Application path)
public class RestaurantController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private RestaurantRepository restaurantRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewRestaurant (@RequestParam String name
      , @RequestParam String item, @RequestParam Double price, @RequestParam String description,
      @RequestParam Double latitude, @RequestParam Double longitude) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    Restaurant n = new Restaurant();
    n.setName(name);
    n.setItem(item);
    n.setPrice(price);
    n.setDescription(description);
    n.setLatitude(latitude);
    n.setLongitude(longitude);
    restaurantRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Restaurant> getAllRestaurants() {
    // This returns a JSON or XML with the users
    return restaurantRepository.findAll();
  }
}

