# Use root/example as user/password credentials
version: '3.1'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Map the container's port to your host machine
    # Add any necessary environment variables

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080" # Map the container's port to your host machine
    # Add any necessary environment variables
    # Connect backend to a database if required

  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080