# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./mysql/mysql-env.txt
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Map the container's port to your host machine
    # Add any necessary environment variables

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "8080:8080" # Map the container's port to your host machine
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/madrid_eats_db?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root_password

    # Add any necessary environment variables
    # Connect backend to a database if required


  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080